### ISSUE TITLE
Sim can't route "through" counters

### ISSUE THREAD

**Issue by jackmawer** [RHY3756547/FreeSO#19] opened 2016-06-12 14:47 UTC
When clicking into the room past these counters, pictured sim gets very confused.
I expected the pathfinding system to route around the counters through the other doors, but it appears to just give up!
Here is a screenshot of the room in question with the Sim:

!["I could have sworn there was nothing there..."](http://i.imgur.com/6jgEDou.png)

**Comment by RHY3756547** [comment] 2016-06-12 15:00
Not a bug, won't fix (for a long time). Within room routing is too expensive to do on the room routing stage.

There are two stages to TS1 routing: room route and within room. Room route tries to get you to the target position's room, and within room tries to move you through the current room to the destination position (generally a door to the next room in the room route). A benefit of this is that we only need to consider objects within our current room for routing, so it is very fast.

This case does not even have a room route, since the sim is within the same room as the destination. To change this the engine would need to calculate a new room route FROM THE TARGET ROOM to the SAME ROOM, testing every entrance for one that will allow the sim to proceed. This is quite expensive and could cause a very noticable hitch on routing starting.

**Closed by RHY3756547** 2016-06-12 15:00 UTC

**Comment by jackmawer** [comment] 2016-06-12 15:02
Is there a workaround for this?

**Comment by RHY3756547** [comment] 2016-06-12 15:07
Stop segmenting rooms with objects.

**Comment by jackmawer** [comment] 2016-06-12 15:08
Thanks 😜
